services:
  fusiondirectory-app:
    container_name: fusiondirectory-app
    image: docker.io/nfrastack/fusiondirectory:1.5
    labels:
      - traefik.enable=true
      - traefik.http.routers.fusiondirectory.rule=Host(`fusiondirectory.example.com`)
      - traefik.http.services.fusiondirectory.loadbalancer.server.port=80
    volumes:
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver

      - ENABLE_ARGONAUT=FALSE
      - PLUGIN_AUDIT=TRUE
      - PLUGIN_DSA=TRUE
      - PLUGIN_LDAPDUMP=TRUE
      - PLUGIN_LDAPMANAGER=TRUE
      - PLUGIN_MAIL=TRUE
      - PLUGIN_PERSONAL=TRUE
      - PLUGIN_PPOLICY=TRUE
      - PLUGIN_SSH=TRUE
      - PLUGIN_SUDO=TRUE
      - PLUGIN_WEBSERVICE=TRUE

      - LDAP01_NAME=Production
      - LDAP01_HOST=openldap-fusiondirectory
      - LDAP01_PORT=389
      - LDAP01_BASE_DN=dc=example,dc=org
      - LDAP01_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP01_ADMIN_PASS=admin
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
